dist: bionic
language: go
env: GO111MODULE=on GOFLAGS='-mod vendor'
install: true
email: false
go:
  - '1.10'
  - '1.11'
  - '1.12'
  - '1.13'
  - '1.14'
  - 'tip'

script:
     - go test -coverpkg=./... -coverprofile=coverage.info -timeout=5s
     - bash <(curl -s https://codecov.io/bash)